### ISSUE TITLE
Add an optional GUI

### ISSUE THREAD

**Issue by siggib007** [siggib007/PiVault#21]
Learn how to do python GUI by creating an GUI for pivault that you start with a parameter

**Comment by ahall** [comment]
Looking forward to this one, has to be perfectly. designed, looking forward to seeing your graphical skills my friend :D:D

**Comment by siggib007** [comment]
Don't get your hopes up, I'm not a UI nor graphic designer. This will be functional but I would not count on this being pretty.

**Comment by ahall** [comment]
Functional is good enough for me 👯

**Comment by siggib007** [comment]
This is pretty much code complete. Config function is left, and the password reset function isn't integrated correctly. Also need to do regression testing

**Comment by siggib007** [comment]
Also need to improve verification on new add

**Comment by siggib007** [comment]
All that is left is do the config function which will allow you to change the config within the GUI on the fly and save it to a file.

**Comment by siggib007** [comment]
config function complete. Want to add a feature where fields that are not applicable for the selected store are hidden.

**Comment by siggib007** [comment]
dynamic fields have been moved into their own issue. considering this issue done.
